### ISSUE TITLE
Gluin + Open Web Board + Raspberry Pi + Flame / Fx0 味見

### ISSUE THREAD

**Issue by gurezo** [club-wot/ajimikai#5]
バレンタインデー／ホワイトデーハッカソン以来のGluinを使った味見会希望します。
他の味見会と混ぜてもアリ

**Comment by MSakamaki** [comment]
@flatbird さんがGluinをコノハ鯖に立てているとの情報が！

**Comment by gurezo** [comment]
コノハでいきなり構築する勇気が無かったので、atomのPCで実験的に構築しました。
@flatbird :+1:

**Comment by gurezo** [comment]
一旦close
時期が来れば、reOpen
