### ISSUE TITLE
りのべるさんに近々遊びに行く

### ISSUE THREAD

**Issue by gurezo** [club-wot/ajimikai#8]
９月早々に遊び行く日程を決めたいですね。
都合の良い日を書き込んで下さい。

**Comment by gurezo** [comment]
グンマーの希望 9/5 or 9/19が嬉しい

**Comment by MSakamaki** [comment]
９月のダメな日は以下
- ８日
- １２日
- １９日

**Comment by KazukoShikiya** [comment]
しきや、ダメな日は、9/5、9/16、9/23。あとは大丈夫。

**Comment by cigalecigales** [comment]
明確なダメな日は無いです。
決まった日を空けれるようにがんばります！

**Comment by flatbird** [comment]
9/8, 9/29 がダメです。

**Comment by silverskyvicto** [comment]
今のところ9/7, 9/11, 9/15がなんとか空いています。

**Comment by tacoyaky** [comment]
9/7, 8, 11, 17 はダメです。

**Comment by chikoski** [comment]
リノベるさんの空いている日は： 8, 10, 11, 14,  15,  16,  17 でした。

**Comment by chikoski** [comment]
| 日 | 参加可能な人 |
| --- | --- |
| 9/8 | @cigalecigales, @KazukoShikiya |
| 9/10 | @tacoyaky, @flatbird, @cigalecigales, @KazukoShikiya, @MSakamaki, @chikoski , @gurezo |
| 9/11 | @silverskyvicto, @flatbird, @cigalecigales, @KazukoShikiya, @MSakamaki, @chikoski |
| 9/14 | @tacoyaky, @flatbird, @cigalecigales, @KazukoShikiya, @MSakamaki, @chikoski , @gurezo |
| 9/15 | @tacoyaky, @silverskyvicto, @flatbird, @cigalecigales, @KazukoShikiya, @MSakamaki, @chikoski , @gurezo |
| 9/16 | @tacoyaky, @flatbird, @cigalecigales, @MSakamaki, @chikoski , @gurezo |
| 9/17 | @flatbird, @cigalecigales, @KazukoShikiya, @MSakamaki |

**Comment by chikoski** [comment]
15が第1候補、第2候補が14で進めますね。

**Comment by clubwot** [comment]
:+1:

**Comment by MSakamaki** [comment]
:+1:

**Comment by chikoski** [comment]
15日で場所を仮押さえしました。明日あたりに本決まりにしようと思っています。

**Comment by gurezo** [comment]
:+1:

**Comment by chikoski** [comment]
15日、先方がダメということなので、14日になりました。

**Comment by chikoski** [comment]
先方にあったデバイス：
- [Philips Hue](http://www2.meethue.com/ja-JP)
- [BOCCO](http://www.ux-xu.com/product/bocco)
- Bravia
- [Wemo](http://www.belkin.com/us/F7C027/p/P-F7C027/)
- Amazonのスピーカーみたいなアレ
- [Qrio smart lock](http://qrio.me/smartlock/)
- [ロボット掃除機COCOROBO](http://www.sharp.co.jp/cocorobo/)

**Comment by chikoski** [comment]
ロボット掃除機 x Bravia x Hue とかで、何かできるといいなあ。

**Comment by MSakamaki** [comment]
cocoroboが面白そうなので、自分用の備忘録かねてAPIのリンク貼っておきますね。
https://developer.cloudlabs.sharp.co.jp/clabsapi-web/

https://developer.cloudlabs.sharp.co.jp/clabsapi-web/document/api/cocorobo/
